# Generated by Django 3.1.7 on 2021-03-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210303_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
